# Generated by Django 5.0.3 on 2025-12-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0005_add_clerk_user_id_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
