# Generated by Django 5.0.3 on 2025-12-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0007_flashcard_note_quiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="document",
            name="source_type",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("web", "Web")], default="pdf", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="source_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
